[metadata]
name = thermal-vision-materials
version = 0.1.0
description = Thermal vision materials, dataset simulation and robot-simulation
author = MarinaP
license = MIT

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.8
include_package_data = True

[options.entry_points]
console_scripts =
    thermal-ingest = thermal_sensors.scripts.ingest:main
    thermal-preprocess = thermal_sensors.scripts.preprocess:main